query GET_DIENST_BY_URI($uri: String) {
  dienstBy(uri: $uri) {
    dienstId
    title
    slug
    content
    acfDiensten {
      illustrationName
      whiteContent
    }
    acfFlex {
      flex {
        __typename
        ... on Dienst_Acfflex_Flex_Content {
          content
        }
        ... on Dienst_Acfflex_Flex_Case {
          order
          content
          image {
            sourceUrl
            altText
            mediaDetails {
              sizes {
                sourceUrl
                width
              }
            }
          }
        }
        ... on Dienst_Acfflex_Flex_CallToAction {
          content
          button {
            target
            title
            url
          }
        }
      }
    }
  }
}
