query GetLocaties {
  locaties(where: {orderby: {field: MENU_ORDER, order: ASC}}) {
    nodes {
      title
      acfLocaties {
        adres
      }
      featuredImage {
        sourceUrl
        altText
        mediaDetails {
          sizes {
            sourceUrl
            width
          }
        }
      }
    }
  }
}

