query GET_PAGES {
  pages(where: {orderby: {field: MENU_ORDER, order: ASC}}) {
    edges {
      node {
        title
        content
        slug
        acfFlex {
          flex {
            __typename
          }
        }
      }
    }
  }
}

