query GET_PAGE_BY_URI($uri: String) {
  pageBy(uri: $uri) {
    pageId
    title
    content
    slug
    acfFlex {
      flex {
        __typename
        ... on Page_Acfflex_Flex_Content {
          content
        }
        ... on Page_Acfflex_Flex_Case {
          order
          content
          image {
            sourceUrl
            altText
            mediaDetails {
              sizes {
                sourceUrl
                width
              }
            }
          }
        }
        ... on Page_Acfflex_Flex_CallToAction {
          content
          button {
            target
            title
            url
          }
        }
      }
    }
  }
}

