query GetTeam {
  team(where: {orderby: {field: MENU_ORDER, order: ASC}}) {
    nodes {
      title
      excerpt
      featuredImage {
        node{
        sourceUrl
        altText
        mediaDetails {
          sizes {
            sourceUrl
            width
          }
        }
      }
      }
    }
  }
}

