query GetToolbox {
  toolbox(where: {orderby: {field: MENU_ORDER, order: ASC}}) {
    nodes {
      title
      content
      featuredImage {
        node {
        sourceUrl
        altText
        mediaDetails {
          sizes {
            sourceUrl
            width
          }
        }
      }
      }
    }
  }
}

